from math import sqrt, pi, atan2, sin, cos, radians, degrees
import numpy as np
from scipy.interpolate import griddata
from scipy.io import loadmat
from scipy.sparse import csr_matrix
import cvxpy as cp
import configparser
import geod_transform
from disloc3d import dc3d_wrapper
import visc_tools
import force_couple
from scipy.linalg import lstsq

# put this into a function...

config = configparser.ConfigParser()
config.read("params.cfg")
fault_params = config["Fault Info"]
slip_params = config["Slip Patch Descritization"]
geometry_params = config["Geometry"]
viscoelastic_params = config["Viscoelastic Parameters"]
geometry_params = config["Geometry"]
data_params = config["Datasets"]

lat0 = float(geometry_params["Lat0"])
lon0 = float(geometry_params["Lon0"])
h0 = float(geometry_params["h0"])

# global constants
nu = float(viscoelastic_params["nu"])
Gshear = float(viscoelastic_params["Gshear"])
dlock_max = float(slip_params["dlock_max"])

# fault discretization parameters
vert_els = int(slip_params["nve_total"])
pL = int(slip_params["patch_length"])

# other things
variable_rake = fault_params.getboolean("variable_rake")

# viscoelastic parameters
Nterms = int(viscoelastic_params["Nterms"])

H1 = float(viscoelastic_params["H1"])
H2 = float(viscoelastic_params["H2"])
tR1 = float(viscoelastic_params["tR1"])
tR2 = float(viscoelastic_params["tR2"])
coseismic_slip = float(viscoelastic_params["coseismic_slip"])
t_eq_frac = float(viscoelastic_params["t_eq_frac"])

"""
    get_observation_coords is specific to the formatting in this provided strain_rate_observation file.
    It assumes input coordinates are in lon/lat (wgs84) and that the params.cfg file contains information
    about the scale of the observation data. 

    It also assumes that strain rate data is formatted as Exx, Exy, Eyy.

    Feeding in lon0 and lat0 rather than using global constants from params.cfg because
    I'm testing two different geometries using csaf = True in main.ipynb
"""
def get_observation_coords(file, mesh, lon0, lat0):
    # get strain rate units
    scale = 1e-6 if data_params.getboolean("is_microstrain") else 1

    data = np.loadtxt(file, delimiter=",")

    # reindex data
    lon, lat = data[:, 0:2].T

    # convert observation data to local coordinates, crop to mesh limits
    x, y, z = geod_transform.geod2enu(lat, lon, 0, lat0, lon0, 0)

    # convert to km
    xyz = np.vstack((x, y, z)).T / 1000

    within_bounds = (
        (xyz[:, 0] > mesh["tri_centroids"][:, 0].min())
        & (xyz[:, 0] < mesh["tri_centroids"][:, 0].max())
        & (xyz[:, 1] > mesh["tri_centroids"][:, 1].min())
        & (xyz[:, 1] < mesh["tri_centroids"][:, 1].max())
    )
    xy_obs = xyz[within_bounds]
    E_means = data[within_bounds, 2:5] * scale
    E_stds = data[within_bounds, 5:8] * scale

    return xy_obs, E_means, E_stds


"""
    This function generates the Okada input geometry for a fault patch 
    defined by its 2D trace (x1, y1 and x2, y2), 
    total depth (not down-dip, but z value), and its dip (degrees).
"""


def get_pm(x1, y1, x2, y2, H, dip):
    xc, yc = (x1 + x2) / 2, (y1 + y2) / 2
    dx, dy = (x2 - x1), (y2 - y1)

    length = sqrt((dx) ** 2 + (dy) ** 2)
    angle = atan2(dy, dx)

    width = H / sin(radians(dip))

    # center of fault x+y is only the center at the surface if dip = 90
    # temp can be thought of as the horizontal distance from the epicenter to the fault surface trace
    # for an earthquake occurring at the center of the fault
    temp = abs(width) * cos(radians(dip))
    xo, yo = (-temp * cos(pi / 2 + angle), -temp * sin(pi / 2 + angle))

    strike = 90 - degrees(angle)
    return np.array((length, width, float(H), dip, strike, xc + xo, yc + yo))

"""
    This function performs piecewise smoothing for segments along a fault.
    Inputs are: 
        -fault object (used for getting number of segments)
        -A1 Greens functions for uniform slip
        -A2 Greens functions for tapered slip
        -for a 5 patch long fault, these correspond to:
           _ _ _ _ _
       A1:             <- uniform slip 
       A2: / / / / /   <- tapered slip (see below)
           0 1 2 3 4
        - where A2 is generated by discretizing the patch into n smaller segments, 
          and weighing each set of GFs more, beginning at 0 and ending at 1. 
        - for 4 smaller segments, each line here is 0.25 * unit slip

          0 1 2 3
                /|
              /  |
            /    |
          /      |
          0 1 2 3
        
    Output:
        -A creates a linear combination of A1 and A2 based on the length of the fault
        -modifies applied slip to taper at edges, e.g.
          _  
        /   \
        0 1 2 
"""


def piecewise_smoothing(n, A1, A2):
    A = np.zeros_like(A1)

    if n == 1:
        A[:, 0] = A1[:, 0]

    else:
        # First patch
        A[:, 0] = A1[:, 0] - A2[:, 0]

        # if 2 patches, python will skip this loop
        for j in range(1, n - 1):
            A[:, j] = A2[:, j - 1] + A1[:, j] - A2[:, j]

        # Last patch
        A[:, n - 1] = A2[:, n - 2] + A1[:, n - 1]

    return A


"""
    This function takes a single fault patch m, defined using the
    Okada geometry, and refines it into nhe horizontal and nve vertical 
    patches, returning them in a list of length nve*nhe 

    input: (7,) numpy array
    output: list contains nhe*nve (7,) numpy arrays
"""


def patchfault(m, nhe, nve):
    # if nhe == 1 & nve == 1:
    #    return([m])
    dip = radians(m[3])
    strike = -radians(m[4])
    sin_dip = sin(dip)
    cos_dip = cos(dip)
    iw = m[0] / nhe
    jw = m[1] / nve
    is_ = np.arange(1, nhe + 1)
    js = np.arange(1, nve + 1)

    n = nhe * nve
    c1 = -m[1] * cos_dip
    c2 = 0.5 * (m[0] + iw)
    c3 = m[2] - nve * jw * sin_dip

    # Calculate midpoints, depths of each patch
    p = np.outer(cos_dip * (jw * js - m[1]), np.ones(nhe))
    q = np.outer(np.ones(nve), (iw * is_) - 0.5 * (m[0] + iw))
    r = np.outer(m[2] - jw * sin_dip * (nve - js), np.ones(nhe))
    mp = np.column_stack((p.flatten(), q.flatten(), r.flatten()))

    # Adjust midpoints for strike
    R = np.array(
        [[cos(strike), -sin(strike), 0], [sin(strike), cos(strike), 0], [0, 0, 1]]
    )
    mp = np.dot(mp, R.T)

    # Adjust midpoints for offset from origin
    mp[:, 0] += m[5]
    mp[:, 1] += m[6]

    patch_models = []

    # Loop through and construct each patch model as a NumPy array
    for i in range(n):
        pm = np.zeros(7)
        pm[0] = iw
        pm[1] = jw
        pm[2] = mp[i, 2]
        pm[3:5] = m[3:5]  # Broadcasting for same values
        pm[5:7] = mp[i, 0:2]
        patch_models.append(pm)

    return patch_models


# Function to interpolate and handle NaN values for all columns at once
def interpolate_all(initial_coords, data, final_coords):
    # Interpolate all columns at once
    interp_data = griddata(
        initial_coords[:, :2], data, final_coords[:, :2], method="linear"
    )

    nan_mask = np.isnan(interp_data)
    if np.any(nan_mask):
        nearest_data = griddata(
            initial_coords[:, :2], data, final_coords[:, :2], method="nearest"
        )
        interp_data[nan_mask] = nearest_data[nan_mask]

    return interp_data


"""
    this function takes in an n by 4 array of segments for a single fault
    and a desired length for each segment
    it will upsample segments to match desired patch length (pL)
    without modifing ends of each segment, thus preserving input traces
    each row: [x1,y1,x2,y2] 
"""


def normalize_fault_segs(many_segs, pL):
    many_segs = np.atleast_2d(many_segs)
    new_segs = []
    index_vector = []

    for idx, (x1, y1, x2, y2) in enumerate(many_segs):
        dist = np.linalg.norm([x2 - x1, y2 - y1])
        nhe = int(np.ceil(dist / pL))  # Number of segments to split into
        xy_interp = np.linspace([x1, y1], [x2, y2], nhe + 1)

        # Create the sub-segments for this segment
        segs = np.column_stack((xy_interp[:-1], xy_interp[1:]))
        new_segs.append(segs)

        # Append the corresponding index for each new segment
        index_vector.extend([idx] * len(segs))

    return np.concatenate(new_segs, axis=0)

class Segment:
    # initialize default parameters as (effectively) a 2D strike slip model
    def __init__(self, segends, parent_fault):
        self.dip = parent_fault.dip
        self.rake = parent_fault.rake
        self.slip = parent_fault.slip
        self.h = parent_fault.h
        # initialize empty arrays for
        self.displacements = []
        self.gradients = []
        self.stresses = []
        self.fine_patches = []
        self.nhe = []
        self.nve = []
        self.parent_fault = parent_fault

        segends = np.array(segends)
        self.geometry = segends.reshape(2, 2)  # pm geometry (segment end points)
        (x1, y1), (x2, y2) = self.geometry
        self.pm = get_pm(x1, y1, x2, y2, self.h, self.dip)
        self.length = self.pm[0]

    def refine_patches(self, refine_length=1e6, nve=1):
        # Generate refined patches from geometry
        self.nhe = np.ceil(self.pm[0] / refine_length).astype(int)
        self.nve = nve

        self.fine_patches = (
            patchfault(self.pm, self.nhe, self.nve)
            if self.nhe > 1 or self.nve > 1
            else [self.pm]
        )

    # uses rake information to get slip vector for dislocation modeling
    # by default assumes unit slip. also assumes zero opening.
    def get_slip(self, perp=False, mag = 1):
        rake = self.rake + 90 if perp else self.rake
        strike_slip, dip_slip = cos(radians(rake)), sin(radians(rake))

        # if less than 1e-6, set to zero
        strike_slip = np.round(strike_slip, 6)
        dip_slip = np.round(dip_slip, 6)

        return [strike_slip * mag, dip_slip * mag, 0 * mag]

    def compute_disloc(self, slip, obs_xy):
        if not self.fine_patches:
            self.refine_patches()

        displacements, gradients, stresses = [], [], []
        for pf in self.fine_patches:

            new_pf = pf.copy()
            # convert to m from km
            new_pf[0:3] = new_pf[0:3] * 1000
            new_pf[5:7] = new_pf[5:7] * 1000
            # problem specific modification
            new_pf[2] += 1e-3
            
            u, g, s = dc3d_wrapper(new_pf, slip, obs_xy * 1000)
            displacements.append(u)
            gradients.append(g)
            stresses.append(s)

        self.displacements = np.array(displacements)
        self.gradients = np.array(gradients)
        self.stresses = np.array(stresses)

    def reshape(self, value):
        return np.array(value).reshape(self.nve, self.nhe, -1)

    def get_strain(self):

        Exx = self.gradients[:, :, 0]
        Exy = 0.5 * (self.gradients[:, :, 1] + self.gradients[:, :, 3])
        Eyy = self.gradients[:, :, 4]
        Exx = self.reshape(Exx)
        Exy = self.reshape(Exy)
        Eyy = self.reshape(Eyy)

        self.Exx = Exx
        self.Exy = Exy
        self.Eyy = Eyy

        return Exx, Exy, Eyy

    def get_disp(self):

        Ue = self.displacements[:, :, 0]
        Un = self.displacements[:, :, 1]
        Uu = self.displacements[:, :, 2]
        self.Ue = self.reshape(Ue)
        self.Un = self.reshape(Un)
        self.Uu = self.reshape(Uu)

    def compute_visco_strain(self, slip, obs_coords, pm = None):

        if pm is None:
            pm = self.pm
        # viscoelastic portion...
        Exx_visc, Exy_visc, Eyy_visc = visc_tools.get_interseismic_strain_rates_cycles(
            pm,
            slip,
            obs_coords[:, 0],
            obs_coords[:, 1],
            self.parent_fault.t_rec,
            self.parent_fault.t_eq,
        )
        return Exx_visc, Exy_visc, Eyy_visc

    def __repr__(self):
        if len(self.displacements) > 0:
            modeled = "Yes"
        else:
            modeled = "No"
        return f"Has GFs: {modeled}, nve,nhe: ({self.nve}, {self.nhe}), Loc: ({self.pm[5]:.1f},{self.pm[6]:.1f})\n"


class Fault:
    def __init__(
        self,
        dip=90,
        rake=0,
        fault_name="None",
        fault_id=0,
        slip=0,
        ub_slip=0,
        lb_slip=0,
        std_slip=0,
        t_rec=0,
        t_eq=0,
        h=1,
    ):
        self.fault_name = fault_name
        self.fault_id = fault_id
        self.dip = dip
        self.rake = rake
        self.slip = slip
        self.ub_slip = ub_slip
        self.lb_slip = lb_slip
        self.std_slip = std_slip
        self.h = h
        self.segments = []

        # if recurrence time is infinite, set it based on slip rate and average coseismic slip
        # coseismic slip (m) * 1000 mm/m * 1/(slip rate (mm/yr)) [=] years
        if np.isinf(t_rec):
            self.t_rec = coseismic_slip * 1000 / self.slip
        else:
            self.t_rec = t_rec

        # if time since earthquake is infinite (e.g. no earthquakes on record)
        # default time since last earthqake as a fraction of recurrence time
        if np.isinf(t_eq):
            self.t_eq = t_eq_frac * self.t_rec
        else:
            self.t_eq = t_eq

    def __repr__(self):
        fault_info = f"Fault(Name: {self.fault_name}, ID: {self.fault_id}, Num Segs: {len(self.segments)}, Dip: {self.dip}, Rake: {self.rake}, Slip: {self.slip})"
        seg_info = "".join(
            [f"    Seg {i}: {segment}" for i, segment in enumerate(self.segments)]
        )  # Indentation added before each segment
        return f"{fault_info}\n{seg_info}"

    def add_segment(self, segends):
        # first we want to normalize the length of the segments
        # this is different from our fine patch refinement...
        segment = Segment(segends, self)
        self.segments.append(segment)
        return segment

    def compute_green_functions(self, piecewise=False):

        # below this is going to go into Fault class...
        E1xx, E1yy, E1xy = [], [], []
        E2xx, E2yy, E2xy = [], [], []

        # Loop through each segment (patch) in the fault
        for patch in self.segments:
            # Compute E1 by summing over all axes
            E1xx.append(patch.Exx.sum(axis=(0,1)))
            E1yy.append(patch.Eyy.sum(axis=(0,1)))
            E1xy.append(patch.Exy.sum(axis=(0,1)))

            if piecewise:
                if patch.nhe == 1:
                    print(
                        "warning: attempting to perform  piecewise smoothing with only one horizontal element."
                    )
                # Compute E2 using a single loop with tapering

                frac = np.arange(patch.nhe) / patch.nhe
                E2xx.append((patch.Exx * frac[:, None]).sum(axis=(0, 1)))
                E2yy.append((patch.Eyy * frac[:, None]).sum(axis=(0, 1)))
                E2xy.append((patch.Exy * frac[:, None]).sum(axis=(0, 1)))

        if piecewise:
            # Apply piecewise smoothing on computed displacements
            num = len(self.segments)
            self.GExx = piecewise_smoothing(num, np.array(E1xx).T, np.array(E2xx).T)
            self.GExy = piecewise_smoothing(num, np.array(E1xy).T, np.array(E2xy).T)
            self.GEyy = piecewise_smoothing(num, np.array(E1yy).T, np.array(E2yy).T)

            self.G1Exx = np.array(E1xx).T
            self.G1Exy = np.array(E1xy).T
            self.G1Eyy = np.array(E1yy).T

            self.G2Exx = np.array(E2xx).T
            self.G2Exy = np.array(E2xy).T
            self.G2Eyy = np.array(E2yy).T

        else:
            self.GExx = np.array(E1xx).T
            self.GEyy = np.array(E1yy).T
            self.GExy = np.array(E1xy).T

def make_fault_from_matlab(one_fault, height):

    def extract_scalar(value):
        while isinstance(value, np.ndarray) and value.size == 1:
            value = value.item() 
        return value

    result = {}
    for key in one_fault.dtype.fields.keys():
        value = extract_scalar(one_fault[key])

        if isinstance(value, np.ndarray) and value.size == 0:
            value = None

        result[key] = value

    f1 = Fault(
        dip=result["Dip"],
        rake=result["Rake"],
        fault_id=result["FaultID"],
        fault_name=result["FaultName"],
        slip=result["PrefSlipRate"],
        ub_slip=result["UBSlipRate"],
        lb_slip=result["LBSlipRate"],
        std_slip=result["STDSlipRate"],
        t_rec=result["RecurrenceTime"],
        t_eq=result["TimeSinceEq"],
        h=height,
    )

    return f1


"""
helper function to make faults from dataframe
could easily be made redundant by standardizing Fault class
to your fault data
example usage:

FaultInfo = gpd.read_file("data/FaultInfo_xy.geojson")
faults_list = []
for idx, fault in FaultInfo.iterrows():
   f_tmp = make_fault_from_dataframe(fault, dlock_max / 3)
   faults_list.append(f_tmp)
"""
def make_fault_from_dataframe(one_fault, height):

    fault = Fault(
        dip=one_fault["dip"],
        rake=one_fault["rake"],
        fault_id=one_fault["ID"],
        fault_name=one_fault["name"],
        slip=one_fault["slip_rate"],
        ub_slip=one_fault["slip_ub"],
        lb_slip=one_fault["slip_lb"],
        std_slip=one_fault["slip_std"],
        t_rec=one_fault["recurrence_int"],
        t_eq=np.nan,
        h=height,
    )
    return fault


def build_smoothness_matrices(pm_top, pm_top_seg_id, pm, nve):
    # smoothing matrix
    # remove nve as argument and manually load that from cfg file

    list_id = np.unique(pm_top_seg_id)
    N = pm_top.shape[0]
    total_patches = N + pm.shape[0]

    # first double check the dimensions are the same...
    if total_patches != nve * N:
        raise (
            ValueError(
                "Incorrect dimensions. len(pm_top)*nve should equal total number of patches"
            )
        )

    pm_smooth_hz = np.zeros((total_patches, total_patches))
    pm_smooth_vert = np.zeros((total_patches, total_patches))

    for segment_id in list_id:
        # Get indices of patches belonging to the current segment
        patch_indices = np.where(pm_top_seg_id == segment_id)[0]

        for j, patch_idx in enumerate(patch_indices):
            # Horizontal smoothness for the top row
            if j < len(patch_indices) - 1:  # Ensure we don't exceed the array length
                pm_smooth_hz[patch_idx, patch_idx] = 1
                pm_smooth_hz[patch_idx, patch_indices[j + 1]] = (
                    -1
                )  # Smooth patch to the left

            # Vertical smoothness for the top row
            pm_smooth_vert[patch_idx, patch_idx] = 1
            pm_smooth_vert[patch_idx, N + (nve - 1) * patch_idx] = (
                -1
            )  # Smooth patch below

            # Additional rows for vertical elements
            for m in range(nve - 2):  # Loop over additional vertical elements
                base_idx = N + (nve - 1) * patch_idx + m
                pm_smooth_vert[base_idx, base_idx] = 1
                pm_smooth_vert[base_idx, base_idx + 1] = (
                    -1
                )  # Smooth patch to the next vertical element

                if j < len(patch_indices) - 1:
                    pm_smooth_hz[base_idx, base_idx] = 1
                    pm_smooth_hz[base_idx, base_idx + (nve - 1)] = (
                        -1
                    )  # Smooth to the left

    # Combine horizontal and vertical smoothness matrices after removing zero rows
    pm_smooth_hz = pm_smooth_hz[np.any(pm_smooth_hz != 0, axis=1)]
    pm_smooth_vert = pm_smooth_vert[np.any(pm_smooth_vert != 0, axis=1)]
    pm_smooth = np.vstack((pm_smooth_hz, pm_smooth_vert))

    return pm_smooth


class build_GFs:
    def __init__(
        self,
        FaultInfo,
        mesh,
        obs_xyz,
        dlock_max,
        pL,
        total_nve,
        variable_rake,
        include_moment,
        calc_visco,
        tri_mom,
        use_gaussian_prior,
        nu,
    ):
        self.mesh = mesh
        self.obs_xyz = obs_xyz
        self.variable_rake = variable_rake
        self.include_moment = include_moment
        self.tri_mom = tri_mom
        self.calc_visco = calc_visco
        self.nu = nu
        self.faults_top = []
        self.faults_bot = []

        self.G_top = {key: [] for key in ["Exx", "Exy", "Eyy"]}
        self.G_bot = {key: [] for key in ["Exx", "Exy", "Eyy"]}

        if self.calc_visco:
            self.G_top_cycle = {key: [] for key in ["Exx", "Exy", "Eyy"]}
            self.G_bot_cycle = {key: [] for key in ["Exx", "Exy", "Eyy"]}

        if variable_rake:

            self.G_top_perp = {key: [] for key in ["Exx", "Exy", "Eyy"]}
            self.G_bot_perp = {key: [] for key in ["Exx", "Exy", "Eyy"]}

            if self.calc_visco:
                self.G_top_cycle_perp = {key: [] for key in ["Exx", "Exy", "Eyy"]}
                self.G_bot_cycle_perp = {key: [] for key in ["Exx", "Exy", "Eyy"]}

        self.FaultInfo = FaultInfo
        self.dlock_max = dlock_max
        self.pL = pL
        self.total_nve = total_nve

        self.use_gaussian_prior = use_gaussian_prior

    def make_fault_lists(self, top=True):

        fault_list = self.faults_top if top else self.faults_bot

        # how deep should pm extend? if top, divide by total_nve, else use dlock_max
        fault_depth = self.dlock_max / self.total_nve if top else self.dlock_max

        # subdivide into 1 km patches for top, don't subdivide (using arbitrarily high refine_length) for bottom
        refine_length = 1 if top else 1e6

        nve = 1 if top else self.total_nve

        for matlab_fault in self.FaultInfo:

            fault = make_fault_from_matlab(matlab_fault, fault_depth)
            segends = normalize_fault_segs(matlab_fault["SegEnds"].item(), self.pL)

            # manual shift around singularity...
            if fault.fault_name == "Calaveras (south)" and top:
                segends[2] += 0.01

            for segment in segends:
                patch = fault.add_segment(segment)

                patch.refine_patches(nve=nve, refine_length=refine_length)

                # for lower patches, remove top layer
                if not top:
                    patch.fine_patches = patch.fine_patches[patch.nhe :]
                    patch.nve -= patch.nhe

            fault_list.append(fault)

    def get_top_gfs(self, perp=False):
        fault_list = self.faults_top
        G = self.G_top_perp if perp else self.G_top
        G_cycle = (
            self.G_top_cycle_perp
            if (self.calc_visco and perp)
            else self.G_top_cycle if self.calc_visco else None
        )

        for fault in fault_list:
            for patch in fault.segments:

                slip = patch.get_slip(perp)

                patch.compute_disloc(slip, self.mesh["tri_centroids"])
                patch.get_strain()

                if self.calc_visco:

                    E_visc = patch.compute_visco_strain(slip, self.obs_xyz)

                    for key, value in zip(G_cycle, E_visc):
                        G_cycle[key].append(value)

            # Builds GExx, GEyy, GExy for each fault
            fault.compute_green_functions(piecewise=True)

            # append these to G_top_fine
            for key, value in zip(G, [fault.GExx, fault.GExy, fault.GEyy]):
                G[key].append(value)

        for key in G:
            G[key] = interpolate_all(
                self.mesh["tri_centroids"], (np.concatenate(G[key], axis=1)), self.obs_xyz
            )
            if self.calc_visco:
                G_cycle[key] = np.array(G_cycle[key]).T

    def get_bot_gfs(self, perp=False):

        fault_list = self.faults_bot

        G = self.G_bot_perp if perp else self.G_bot
        G_cycle = (
            self.G_bot_cycle_perp
            if (self.calc_visco and perp)
            else self.G_bot_cycle if self.calc_visco else None
        )

        for fault in fault_list:
            for patch in fault.segments:

                slip = patch.get_slip(perp)

                patch.compute_disloc(slip, self.mesh["tri_centroids"])
                patch.get_strain()

                for key, value in zip(G, [patch.Exx, patch.Exy, patch.Eyy]):
                    G[key].append(value.sum(axis=1))

                # insteads of just calling for each patch, loop through vertical elements and run viscoelastic GFs on all elements
                if self.calc_visco:
                    for i in range(patch.nve):
                        pm_vert = patch.fine_patches[i * patch.nhe]

                        E_visc = patch.compute_visco_strain(slip, self.obs_xyz, pm=pm_vert)

                        for key, value in zip(G_cycle, E_visc):
                            G_cycle[key].append(value)

        for key in G:
            G[key] = interpolate_all(
                self.mesh["tri_centroids"], (np.concatenate(G[key]).T), self.obs_xyz
            )

            if self.calc_visco:
                G_cycle[key] = np.array(G_cycle[key]).T

    def get_smoothing(self):
        # unwrap patch models to arrays

        pm_top = np.array([s.pm for f in self.faults_top for s in f.segments])
        pm = np.array(
            [p for f in self.faults_bot for s in f.segments for p in s.fine_patches]
        )

        self.num_slip = len(pm_top) + len(pm)

        pm_top_seg_id = np.array(
            [f.fault_id for f in self.faults_top for s in f.segments]
        )

        # create smoothness matrix
        self.pm_smooth = build_smoothness_matrices(
            pm_top, pm_top_seg_id, pm, self.total_nve
        )
        self.pm = pm
        self.pm_top = pm_top

    def process_moment_source(self):
        if not self.include_moment:
            return None

        if self.tri_mom:
            print(
                "Performing triangular moment source calculations. This is time intensive."
            )
            G_mom = force_couple.buildG_MomentSource_2d_tri(
                self.mesh, self.obs_xyz, self.nu
            )
        else:
            G_mom = force_couple.buildG_MomentSource_2d(
                self.mesh, self.obs_xyz, self.nu
            )
        G_mom_reshaped = []
        for E_component in G_mom.values():
            G_mom_reshaped.extend(
                np.hstack([values for values in E_component.values()])
            )
        self.G_mom = np.array(G_mom_reshaped) * 1e-3
        self.num_mom = self.G_mom.shape[1]

    def compute_all(self):
        self.make_fault_lists(top=True)

        self.make_fault_lists(top=False)
        self.get_smoothing()

        print("Calculating shallow patch Green's Functions")
        self.get_top_gfs(perp=False)
        print("Calculating deep patch Green's Functions")
        self.get_bot_gfs(perp=False)

        if self.variable_rake:

            print("Calculating perpendicular rake shallow patch Green's Functions")
            self.get_top_gfs(perp=True)
            print("Calculating perpendicular rake deep patch Green's Functions")
            self.get_bot_gfs(perp=True)

        if self.include_moment:
            print("Calculating moment source Green's Functions")
            self.process_moment_source()

        else:
            self.G_mom = None

    def return_greens(self):
        return {
            "G_top": self.G_top,
            "G_top_cycle": self.G_top_cycle if self.calc_visco else None,
            "G_bot": self.G_bot,
            "G_bot_cycle": self.G_bot_cycle if self.calc_visco else None,
            "G_top_perp": self.G_top_perp if self.variable_rake else None,
            "G_top_cycle_perp": (
                self.G_top_cycle_perp
                if (self.variable_rake and self.calc_visco)
                else None
            ),
            "G_bot_perp": self.G_bot_perp if self.variable_rake else None,
            "G_bot_cycle_perp": (
                self.G_bot_cycle_perp
                if (self.variable_rake and self.calc_visco)
                else None
            ),
            "G_mom": self.G_mom if self.include_moment else None,
        }


class Inversion:
    def __init__(self, GF_obj, d, Esig):

        self.G_top = getattr(GF_obj, "G_top", None)
        self.G_bot = getattr(GF_obj, "G_bot", None)

        self.G_top_perp = getattr(GF_obj, "G_top_perp", None)
        self.G_bot_perp = getattr(GF_obj, "G_bot_perp", None)

        self.G_top_cycle = getattr(GF_obj, "G_top_cycle", None)
        self.G_bot_cycle = getattr(GF_obj, "G_bot_cycle", None)

        self.G_top_cycle_perp = getattr(GF_obj, "G_top_cycle_perp", None)
        self.G_bot_cycle_perp = getattr(GF_obj, "G_bot_cycle_perp", None)

        self.G_mom = getattr(GF_obj, "G_mom", None)
        self.num_mom = getattr(GF_obj, "num_mom", 0)
        self.num_slip = getattr(GF_obj, "num_slip", 0)

        self.obs_xyz = GF_obj.obs_xyz
        self.num_slip = GF_obj.num_slip
        self.mesh = GF_obj.mesh
        self.nu = GF_obj.nu
        self.pm_smooth = GF_obj.pm_smooth
        self.Esig = Esig
        self.d = d

        self.faults_top = GF_obj.faults_top
        self.faults_bot = GF_obj.faults_bot

        self.pm_top = GF_obj.pm_top
        self.pm = GF_obj.pm

        self.calc_visco = GF_obj.calc_visco
        self.variable_rake = GF_obj.variable_rake
        self.include_moment = GF_obj.include_moment
        self.tri_mom = getattr(GF_obj, "tri_mom")
        self.use_gaussian_prior = getattr(GF_obj,"use_gaussian_prior", False)

        # run some basic input checks
        if not self.G_top and not self.G_bot:
            raise ValueError("No GFs found. Please run build_GFs first.")

        if not (self.G_top_perp or self.G_bot_perp) and self.variable_rake:
            raise ValueError("No perpendicular GFs found. Check variable_rake flag.")

        if not (self.G_top_cycle or self.G_bot_cycle) and self.calc_visco:
            raise ValueError("No viscoelastic GFs found. Check calc_visco flag.")

        if not (self.G_top_cycle_perp or self.G_bot_cycle_perp) and (self.calc_visco and self.variable_rake):
            raise ValueError("No perpendicular viscoelastic GFs found. Check variable_rake and calc_visco flags.")

        self.G = None
        self.ub = None
        self.lb = None
        self.GG = None
        self.dd = None

    def build_G(self):

        G_upper = {"Exx": [], "Exy": [], "Eyy": []}
        G_main = {"Exx": [], "Exy": [], "Eyy": []}

        if self.variable_rake:
            G_upper_perp = {"Exx": [], "Exy": [], "Eyy": []}
            G_main_perp = {"Exx": [], "Exy": [], "Eyy": []}

        for key in G_main:

            # make negative because we're solving for backslip
            # if self.use_elastic:
            G_upper[key] = -self.G_top[key]
            G_main[key] = -self.G_bot[key]

            if self.variable_rake:
                G_upper_perp[key] = -self.G_top_perp[key]
                G_main_perp[key] = -self.G_bot_perp[key]

            if self.calc_visco:
                G_upper[key] += 1000 * self.G_top_cycle[key] * 1e-6
                G_main[key] += 1000 * self.G_bot_cycle[key] * 1e-6

                if self.variable_rake:
                    G_upper_perp[key] += 1000 * self.G_top_cycle_perp[key] * 1e-6
                    G_main_perp[key] += 1000 * self.G_bot_cycle_perp[key] * 1e-6
        G = []
        for key in G_main:
            G.extend(np.hstack((G_upper[key], G_main[key])))

        self.G = np.array(G)
        if self.variable_rake:
            G_perp = []
            for key in G_main_perp:
                G_perp.extend(np.hstack((G_upper_perp[key], G_main_perp[key])))
            self.G_perp = np.array(G_perp)
            self.G = np.hstack((self.G, G_perp))

        if self.include_moment:

            self.G = np.hstack((self.G, self.G_mom))

    def set_bounds(
        self,
        use_upper_bounds=True,
        use_lower_bounds=False,
        scale_upper_bounds=10,
        scale_lower_bounds=1,
    ):
        upper_bound_top = np.array(
            [
                fault.ub_slip
                for fault in self.faults_top
                for segment in fault.segments
                for _ in range(segment.nve)
            ]
        )
        upper_bound = np.array(
            [
                fault.ub_slip
                for fault in self.faults_bot
                for segment in fault.segments
                for _ in range(segment.nve)
            ]
        )
        lower_bound_top = np.array(
            [
                fault.lb_slip
                for fault in self.faults_top
                for segment in fault.segments
                for _ in range(segment.nve)
            ]
        )
        lower_bound = np.array(
            [
                fault.lb_slip
                for fault in self.faults_bot
                for segment in fault.segments
                for _ in range(segment.nve)
            ]
        )

        if use_upper_bounds:
            ub = np.hstack((upper_bound_top, upper_bound)) / 1000  # Convert to meters
            if self.variable_rake:
                ub = np.tile(ub, 2)
            if self.include_moment:
                mom_ub = np.full(self.G.shape[1] - len(ub), np.inf)
                ub = np.hstack((ub, mom_ub))
        else:
            ub = np.full(self.G.shape[1], np.inf)

        if use_lower_bounds:
            lb = np.hstack((lower_bound_top, lower_bound)) / 1000
            if self.variable_rake:
                lb = np.tile(lb, 2)
            if self.include_moment:
                mom_lb = np.full(self.G.shape[1] - len(lb), -np.inf)
                lb = np.hstack((lb, mom_lb))
        else:
            lb = np.zeros(lower_bound.shape[0] + lower_bound_top.shape[0])
            if self.variable_rake:
                lb_rake = -np.hstack((upper_bound_top, upper_bound)) / 1000
                lb = np.hstack((lb, lb_rake))
            if self.include_moment:
                mom_lb = np.full(self.G.shape[1] - len(lb), -np.inf)
                lb = np.hstack((lb,  mom_lb))

        self.ub = ub * scale_upper_bounds
        self.lb = lb * scale_lower_bounds

    def get_priors(self, use_bounds_for_std = True):
        std_scale = 0.1
        mean_s_prior = np.array([f.slip for f in self.faults_top for p in f.segments])
        mean_s_prior = 1e-3 * np.hstack((mean_s_prior, np.array([f.slip for f in self.faults_bot for p in f.segments for pf in p.fine_patches])))
        if use_bounds_for_std:
            std_s_prior = np.array([f.ub_slip - f.lb_slip for f in self.faults_top for p in f.segments])
            std_s_prior = std_scale * 1e-3 * np.hstack((std_s_prior, np.array([f.ub_slip-f.lb_slip for f in self.faults_bot for p in f.segments for pf in p.fine_patches])))

            if np.any(std_s_prior <= 0):
                print("Warning: for some faults, upper and lower bounds are equal. Setting their std dev to 10 mm/yr")
                std_s_prior[std_s_prior<=0] = 10/1000
            else:
                std_s_prior = np.array([f.std_slip for f in self.faults_top for p in f.segments])
                std_s_prior = 1e-3 * np.hstack((std_s_prior, np.array([f.std_slip for f in self.faults_bot for p in f.segments for pf in p.fine_patches])))

        self.mean_s_prior = mean_s_prior
        self.std_s_prior = std_s_prior

    def normalize_and_weight(self, weight_smooth = 1e3, weight_rake = 1e3, weight_moment = 1e3):

        W = self.pm_smooth * weight_smooth

        if self.variable_rake:
            W = np.tile(W, 2)
        if self.include_moment:
            W = np.hstack((W, np.zeros((self.pm_smooth.shape[0], self.num_mom))))
        self.W = W

        if self.use_gaussian_prior:
            self.get_priors()
            # Construct Gprior for variable rake
            Gprior = np.diag(1.0 / self.std_s_prior)
            # stack zeros for variable rake Prior...
            Gprior = np.hstack((Gprior, np.zeros_like(Gprior))) if self.variable_rake else Gprior
            Gprior = np.hstack((Gprior, np.zeros((self.num_slip, self.num_mom)))) if self.include_moment else Gprior
            # Construct dd and GG
            self.GG = np.vstack((self.G / np.tile(self.Esig.reshape(-1, 1), self.G.shape[1]), Gprior, W))
            dd = np.concatenate((self.d / self.Esig, self.mean_s_prior / self.std_s_prior, np.zeros(self.pm_smooth.shape[0])))
            self.Gprior = Gprior
        else:
            # Construct dd and GG without Gaussian prior
            self.GG = np.vstack((self.G / np.tile(self.Esig.reshape(-1, 1), self.G.shape[1]), W))
            dd = np.concatenate((self.d / self.Esig, np.zeros((self.pm_smooth.shape[0]))))

        # if using variable rake, add in perpendicular damping terms
        if self.variable_rake:
            eye_slip = np.eye(self.num_slip)
            Gdamp_perp = np.hstack((np.zeros_like(eye_slip), weight_rake * eye_slip))

            if self.include_moment:
                Gdamp_perp = np.hstack(
                    (Gdamp_perp, np.zeros((self.num_slip, self.num_mom)))
                )
            self.Gdamp_perp = Gdamp_perp
            self.GG = np.vstack((self.GG, Gdamp_perp))
            dd = np.hstack((dd, np.zeros(self.num_slip)))

        # if using moment, add in moment damping terms
        if self.include_moment:

            Gdamp_mom = np.zeros((self.num_mom, self.num_slip))

            if self.variable_rake:
                Gdamp_mom = np.tile(Gdamp_mom, 2)

            self.Gdamp_mom = np.hstack((Gdamp_mom, weight_moment * np.eye(self.num_mom)))

            self.GG = np.vstack((self.GG, self.Gdamp_mom))
            dd = np.hstack((dd, np.zeros(self.num_mom)))

        # self.GG = GG
        self.dd = dd

    def run_inversion(self, verbose=False):
        # sparse solution doesn't substantially speed up the problem
        # could be removed to save a trivial amount of time for smaller
        # problems or included to save time on larger problems

        # Convert GG to a sparse matrix
        GG_sparse = csr_matrix(self.GG)

        # Define the optimization variables
        mhat = cp.Variable(GG_sparse.shape[1])

        # Define the objective function
        objective = cp.Minimize(cp.sum_squares(GG_sparse @ mhat - self.dd))

        # Define the bounds
        constraints = [mhat >= self.lb, mhat <= self.ub]

        # Solve the problem
        problem = cp.Problem(objective, constraints)
        problem.solve(
            solver=cp.OSQP, verbose=verbose
        )  # solver=cp.CLARABEL (default) works as well. OSQP seems to be faster for this problem

        # Get the solution
        self.mhat = mhat.value

        slip_idx = self.num_slip * (self.variable_rake + 1)

        self.mhat_bs = self.mhat[:slip_idx]
        if self.include_moment:
            self.mhat_mom = self.mhat[slip_idx:]

        self.dhat = self.G @ self.mhat
        self.chi2 = (
            (self.d / self.Esig - self.dhat / self.Esig)
            @ (self.d / self.Esig - self.dhat / self.Esig)
            / len(self.d)
        )
        self.dhat = self.dhat
        self.data_Var = self.d @ self.d
        self.resid_Var = (self.d - self.dhat) @ (self.d - self.dhat)
        self.var_red = 1 - self.resid_Var / self.data_Var

        print(f"Chi-2: {self.chi2:.2f}")

    def post_process(self):

        ndat = len(self.d)//3
        Exx_mean = self.d[:ndat]
        Exy_mean = self.d[ndat:2*ndat]
        Eyy_mean = self.d[2*ndat:]

        pm_top = np.array([s.pm for f in self.faults_top for s in f.segments])
        pm = np.array(
            [p for f in self.faults_bot for s in f.segments for p in s.fine_patches]
        )
        area_top = np.prod(pm_top[:, :2], axis=1) * 1e6
        area_bot = np.prod(pm[:, :2], axis=1) * 1e6

        rake_top_patches = np.array(
            [s.rake for f in self.faults_top for s in f.segments]
        )
        rake_patches = np.array(
            [
                s.rake
                for f in self.faults_bot
                for s in f.segments
                for pf in s.fine_patches
            ]
        )

        NN = len(self.dhat) // 3
        Exx_tot = self.dhat[:NN]
        Exy_tot = self.dhat[NN : 2 * NN]
        Eyy_tot = self.dhat[2 * NN :]

        slip_idx = self.num_slip * (self.variable_rake + 1)

        dhat_bs = self.G[:, :slip_idx] @ self.mhat_bs
        Exx_bs = dhat_bs[:NN]
        Exy_bs = dhat_bs[NN : 2 * NN]
        Eyy_bs = dhat_bs[2 * NN :]

        if self.include_moment:
            dhat_mom = self.G[:, slip_idx:] @ self.mhat_mom
            Exx_bf = dhat_mom[:NN]
            Exy_bf = dhat_mom[NN : 2 * NN]
            Eyy_bf = dhat_mom[2 * NN :]

        max_shear = np.sqrt((Exx_mean - Eyy_mean) ** 2 + Exy_mean**2) * 1e6
        max_shear_bs = np.sqrt((Exx_bs - Eyy_bs) ** 2 + Exy_bs**2) * 1e6
        max_shear_bf = (
            np.sqrt((Exx_bf - Eyy_bf) ** 2 + Exy_bf**2) * 1e6
            if self.include_moment
            else np.zeros_like(max_shear_bs)
        )
        max_shear_tot = np.sqrt((Exx_tot - Eyy_tot) ** 2 + Exy_tot**2) * 1e6

        dilatation = 1e6 * (Exx_mean + Eyy_mean)
        dilatation_bs = 1e6 * (Exx_bs + Eyy_bs)
        dilatation_bf = 1e6 * (Exx_bf + Eyy_bf) if self.include_moment else 0
        dilatation_tot = 1e6 * (Exx_tot + Eyy_tot)

        max_shear_resid = 1e6 * np.sqrt(
            ((Exx_mean - Exx_tot) - (Eyy_mean - Eyy_tot)) ** 2
            + (Exy_mean - Exy_tot) ** 2
        )

        dilatation_resid = 1e6 * (Exx_mean - Exx_tot) + (Eyy_mean - Eyy_tot)

        if self.variable_rake:
            mhat_rake = self.mhat_bs[: self.num_slip]
            mhat_perp = self.mhat_bs[self.num_slip :]
        else:
            mhat_rake = self.mhat_bs

        top_idx = len(area_top)

        bs_top_rake = mhat_rake[:top_idx]
        bs_bot_rake = mhat_rake[top_idx:]

        if self.variable_rake:
            bs_top_perp = mhat_perp[:top_idx]
            bs_bot_perp = mhat_perp[top_idx:]

            bs_top = np.sqrt(bs_top_rake**2 + bs_top_perp**2)
            bs_bot = np.sqrt(bs_bot_rake**2 + bs_bot_perp**2)

        else:
            bs_top = bs_top_rake
            bs_bot = bs_bot_rake

        # compute rake
        if self.variable_rake:
            # Top vectors
            v_r_top_x = bs_top_rake * np.cos(np.radians(rake_top_patches))
            v_r_top_y = bs_top_rake * np.sin(np.radians(rake_top_patches))
            v_p_top_x = bs_top_perp * np.cos(np.radians(rake_top_patches + 90))
            v_p_top_y = bs_top_perp * np.sin(np.radians(rake_top_patches + 90))
            v_tot_top_x = v_r_top_x + v_p_top_x
            v_tot_top_y = v_r_top_y + v_p_top_y
            rake_top = np.degrees(np.arctan2(v_tot_top_y, v_tot_top_x))

            # Bottom vectors
            v_r_bot_x = bs_bot_rake * np.cos(np.radians(rake_patches))
            v_r_bot_y = bs_bot_rake * np.sin(np.radians(rake_patches))
            v_p_bot_x = bs_bot_perp * np.cos(np.radians(rake_patches + 90))
            v_p_bot_y = bs_bot_perp * np.sin(np.radians(rake_patches + 90))
            v_tot_bot_x = v_r_bot_x + v_p_bot_x
            v_tot_bot_y = v_r_bot_y + v_p_bot_y
            rake_bot = np.degrees(np.arctan2(v_tot_bot_y, v_tot_bot_x))
        else:
            rake_top = rake_top_patches
            rake_bot = rake_patches

        # On-fault moment calculation
        mu = 30e9  # shear modulus in N/m^2
        # Note: bs is in m/yr, Areas in m^2, so Mo is in N*m/yr
        self.Mo_fault = mu * np.sum(area_top * bs_top) + mu * np.sum(area_bot * bs_bot)

        # Off-fault moment calculation
        # Here we want to convert the weights (mhat_mom) on the moment sources to units of
        # Moment [Force*distance, N*m]. The moment GFs are unitless.  The weights are moment normalized by plate
        # thickness, H, Area of the triangle, and elastic shear modulus, mu
        # Need to multipiply estimated weights by mu*A*H and unscale the weights by
        # 10^-3 (note that Gmom was already rescaled (for improve scaling
        # for lsq inversion) as Gmom = Gmom*10^-3)

        # An effective depth for off-fault moment sources is required for scaling
        # This ought to be the averge depth over which off-fault sources contributed to surface strain
        # Total off-fault moment scales with this depth.
        # H = depth of off-fault moment  (meters)
        H = 15000; 
        # Off-fault moment calculation (distributed moments)
        # Conversion of weights (mhat_mom) to moments in N*m
        conv = 1e-3*mu*H*self.mesh["tri_areas"]*1e6 # tri_ares in km^2, convert to m^2, conversion factor (see notes above)

        if self.include_moment:
            m11 = self.mhat_mom[: len(self.mhat_mom) // 3] * conv  # dipole, force couple
            m12_m21 = (
                self.mhat_mom[len(self.mhat_mom) // 3 : 2 * len(self.mhat_mom) // 3] * conv
            )  # double couple m12 + m21
            m22 = (
                self.mhat_mom[2 * len(self.mhat_mom) // 3 :] * conv
            )  # dipole, force couple

            # Compute deviatoric moment tensor to get moment (Mo) of double-couple representations
            Mo = []
            for j in range(len(m11)):
                E = np.array(
                    [
                        [m11[j] - (m11[j] + m22[j]) / 2, 0.5 * m12_m21[j]],
                        [0.5 * m12_m21[j], m22[j] - (m11[j] + m22[j]) / 2],
                    ]
                )
                val, _ = np.linalg.eig(E)
                Mo.append(abs(val[0]))

            self.Mo_off = np.sum(Mo) 
        else:
            print('Moment rate explicitly not calculated. Defaulting to zero.')
            self.Mo_off = 0

        # Print moments
        print(f"On-fault moment accumulation rate: {self.Mo_fault:.2e} Nm/yr")
        print(f"Off-fault moment rate (double couples): {self.Mo_off:.2e} Nm/yr")
        print(f"Total (on+off) moment rate: {self.Mo_fault + self.Mo_off:.2e} Nm/yr")
        print(
            f"Percent of total due to on-fault: {self.Mo_fault / (self.Mo_fault + self.Mo_off) * 100:.2f}%"
        )
        print(
            f"Percent of total due to off-fault: {self.Mo_off / (self.Mo_fault + self.Mo_off) * 100:.2f}%"
        )

        self.results = {
            "strain": {
                "Exx_obs": Exx_mean,
                "Exy_obs": Exy_mean,
                "Eyy_obs": Eyy_mean,
                "Exx_tot": Exx_tot,
                "Exy_tot": Exy_tot,
                "Eyy_tot": Eyy_tot,
                "Exx_bs": Exx_bs,
                "Exy_bs": Exy_bs,
                "Eyy_bs": Eyy_bs,
                "Exx_bf": Exx_bf if self.include_moment else None,
                "Exy_bf": Exy_bf if self.include_moment else None,
                "Eyy_bf": Eyy_bf if self.include_moment else None,
            },
            "shear": {
                "max_shear_mean": max_shear,
                "max_shear_bs": max_shear_bs,
                "max_shear_bf": max_shear_bf if self.include_moment else None,
                "max_shear_tot": max_shear_tot,
                "max_shear_resid": max_shear_resid,
            },
            "dilatation": {
                "dilatation_mean": dilatation,
                "dilatation_bs": dilatation_bs,
                "dilatation_bf": dilatation_bf if self.include_moment else None,
                "dilatation_tot": dilatation_tot,
                "dilatation_resid": dilatation_resid,
            },
            "rake": {
                "rake_top_mod": rake_top,
                "rake_bot_mod": rake_bot,
                "rake_top_obs": rake_top_patches,
                "rake_bot_obs": rake_patches,
            },
            "slip": {
                "bs_top_parallel": bs_top_rake,
                "bs_bot_parallel": bs_bot_rake,
                "bs_top_perp": bs_top_perp if self.variable_rake else None,
                "bs_bot_perp": bs_bot_perp if self.variable_rake else None,
                "bs_top_tot": bs_top,
                "bs_bot_tot": bs_bot,
            },
            "area": {
                "area_top": area_top,
                "area_bot": area_bot,
            },
            "moment": {
                "Mo_fault": self.Mo_fault,
                "Mo_off": self.Mo_off,
            },
        }

        return self.results
    def sample_posteriors(self, Nsamples=1000, correlation_distance = 20):

        mhat_unbounded = lstsq(self.GG, self.dd)[0]

        GGG = (self.G.T / self.Esig).T

        # since this changse the dimensions of Cov_s and we do elementwise boolean algebra
        # using Cov_s and our physical locations, I don't know the best way to implement this

        if self.use_gaussian_prior:
            # GGG = np.vstack((GGG, self.Gprior))
            print("Posterior sampling with gaussian prior currently in progress.")
            print("Defaulting to conventional approach.")

        GGGTGGG = GGG.T @ GGG

        if self.include_moment:

            weight_terms = self.W.T @ self.W
            weight_terms += self.Gdamp_mom.T @ self.Gdamp_mom

            if self.variable_rake:
                weight_terms += self.Gdamp_perp.T @ self.Gdamp_perp

            Gsharp = lstsq((GGGTGGG + weight_terms), GGG.T)[0]
        else:
            # will tile pm_smooth if variable_rake is true or else keep it the same shape if false
            pm_comp = np.tile(self.pm_smooth, (1, self.variable_rake + 1)).T @ np.tile(
                self.pm_smooth, (1, variable_rake + 1)
            )
            G_term = GGGTGGG + self.weight_smooth**2 * pm_comp
            G_term += self.G_perp.T @ self.G_perp if self.variable_rake else 0
            Gsharp = lstsq((G_term), GGG.T)[0]

        Cov_s = Gsharp @ Gsharp.T

        pms = np.vstack((self.pm_top, self.pm))

        if self.variable_rake:
            pms = np.vstack((pms, pms))

        stepsize = 0.5 * np.diag(Cov_s) ** 0.5

        all_Ms = np.zeros((self.mhat.shape[0], Nsamples))

        if self.include_moment:
            if self.tri_mom or not self.tri_mom:
                source_xy = np.vstack(
                    (
                        pms[:, 5:7],
                        self.mesh["tri_centroids"][:, :2],
                        self.mesh["tri_centroids"][:, :2],
                        self.mesh["tri_centroids"][:, :2],
                    )
                )
            else:
                source_xy = np.vstack(
                    (
                        pms[:, 5:7],
                        self.mesh["nodes"],
                        self.mesh["nodes"],
                        self.mesh["nodes"]
                    )
                )
        else:
            source_xy = pms[:, 5:7]

        for k in range(len(self.mhat)):

            # Find sources that are strongly correlated with the current source
            distance = np.sqrt(
                (source_xy[k, 0] - source_xy[:, 0]) ** 2
                + (source_xy[k, 1] - source_xy[:, 1]) ** 2
            )

            ind = (np.abs(Cov_s[k, :]) / Cov_s[k, k] > 0.5) & (distance < correlation_distance)
            position = np.where(ind)[0] == k

            inv_Cov_small = np.linalg.inv(Cov_s[ind, :][:, ind])
            mhat_unbounded_small = mhat_unbounded[ind]
            m_small = self.mhat[ind].copy()
            stepsize_small = stepsize[ind]
            UB_small = self.ub[ind]
            LB_small = self.lb[ind]

            Ms = np.zeros((len(m_small), Nsamples))
            m_prev = m_small.copy()

            # Now conduct MCMC sampling of m(ind)
            cnt2 = -1
            log_prob = (
                (m_small - mhat_unbounded_small)
                @ (inv_Cov_small @ (m_small - mhat_unbounded_small))
                * -0.5
            )

            for j in range(Nsamples * len(m_small)):

                cnt = j % len(m_small)
                m_small[cnt] += 2 * (np.random.rand() - 0.5) * stepsize_small[cnt]

                if m_small[cnt] < LB_small[cnt] or m_small[cnt] > UB_small[cnt]:
                    accept = 0
                else:
                    log_prob_trial = -0.5 * np.dot(
                        (m_small - mhat_unbounded_small),
                        np.dot(inv_Cov_small, (m_small - mhat_unbounded_small)),
                    )

                    # Metropolis acceptance rule
                    rat = np.exp(log_prob_trial - log_prob)
                    if rat > 1:
                        accept = 1
                    else:
                        r = np.random.rand()
                        if r < rat:
                            accept = 1
                        else:
                            accept = 0

                if accept == 1:
                    log_prob = log_prob_trial
                    m_prev = m_small.copy()
                else:
                    m_small = m_prev.copy()

                if cnt == 0:
                    cnt2 += 1
                    Ms[:, cnt2] = m_small

            all_Ms[k, :] = Ms[position, :].ravel()

            print(f"Completed {k / len(self.mhat) * 100:.2f} % of samples")

        self.all_Ms = all_Ms
        return all_Ms

    def compute_all(self):
        self.build_G()
        self.set_bounds()
        # can modify inversion weighting parameters as optional arguments into normalize_and_weight()
        if self.tri_mom:
            self.normalize_and_weight(weight_moment = 25000)
        else:
            self.normalize_and_weight(weight_moment = 1000)

        self.run_inversion(verbose = False)
        results = self.post_process()
        return results

# prints out dictionary trees. used for showing results structure
def print_dict_tree(d, indent=0):
    for key, value in d.items():
        print("   " * indent + str(key), end="")

        if isinstance(value, dict):
            print("")
            print_dict_tree(value, indent + 1)
        elif isinstance(value, np.ndarray):
            print(f": np.ndarray, shape={value.shape}")
        else:
            print(": " + type(value).__name__)
